Clean input data before attempting to parse
In issue #1237 I noticed the browser dev tools were highlighting an error:

  SyntaxError: JSON.parse: unexpected character at line 1 column 1
  of the JSON data

A bit of print-statement debugging showed that the json string being emitted
from logsubmit.js was being contaminated somehow. An example (line-wraps added)

  description: 'simple test 3'
  /usr/bin/curl -X POST -H 'Content-Type: multipart/form-data' \
    -F 'logFile=@/tmp/logondemand' -F desc='simple test 3' \
    -F 'variant=volumio' 'http://logs.volumio.org:7171/logs/v1'
  {"status":"OK","link":"http://logs.volumio.org/volumio/Ig63ngo.html"}

Until the cause of this can be tracked down, remove any unwanted text before
or after the json data string before handing it to JSON.parse().