Properly escape double quotes when constructing mpd command strings - respin (#1482)
* Properly escape strings fed to the mpd 'find' command.

Consider this URI beng passed to listAlbumSongs():
  albums://Kalafina/THE%20BEST%20%22Blue%22
which decodes to this:
  albums://Kalafina/THE BEST "Blue"

When the current code constructs an mpd 'find' command, it produces this:
  find album "THE BEST "Blue"" albumartist "Kalafina"
which causes a failure in MpdClient.receive()
  Error:  [5@0] {} Space expected after closing '"'

What we want to send to mpd is:
  find album "THE BEST \"Blue\"" albumartist "Kalafina"

To get this result, we must escape any double quotes within the strings
that are concatenated to form the 'find' command.
No attempt is made to handle the pathological case of the input string
containing '\"'.

* Whitespace fixups

* More instances of strings being fed to mpdClient.sendCommand()

* Last instances fed to mpdClient.sendCommand(), all folder listings

* Fix strings fed to sendMpdCommand()

* Fix instances od sendMpdCommand in upnp_browser

* Fix instances od sendMpdCommand in webradio

Perhaps not really necessary if every track.uri is properly uri-encoded,
but almost certainly won't hurt.